[project]
name = "wan-s2v-14b"
description = "WAN 2.2 S2V model for speech-to-video generation"
type = "custom"

[runtime]
python_version = "3.10"
cuda_version = "11.8"
base_image = "runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel"

[build]
commands = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[server]
port = 8000
health_check = "/health"
handler = "runpod_handler.py"

[resources]
cpu = 4
memory = "16Gi"
gpu = "NVIDIA GeForce RTX 4090"

[scaling]
min_replicas = 0
max_replicas = 3
idle_timeout = 30

[environment]
PYTHONUNBUFFERED = "1"
HF_HOME = "/tmp"
